GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/devops_starter_war_exploded/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}

###
GET http://localhost:8080/information/api/person

###
POST http://localhost:8080/information/api/person
Content-Type: application/json

{
  "firstName": "Created",
  "lastName": "Person",
  "email": "new@mail.dk",
  "phones": [
    {
      "number": 34567890,
      "description": "Mobile (main)"
    }
  ],
  "address": {
    "street": "Creative Street 1",
    "zipcode": 2800
  }
}

###
PUT http://localhost:8080/information/api/person
Content-Type: application/json

{
  "id": 1,
  "firstName": "Updated",
  "lastName": "Person",
  "email": "different@mail.dk",
  "phones": [
    {
      "number": 98765432,
      "description": "Office"
    }
  ],
  "address": {
    "street": "Progressive Street 2",
    "zipcode": 2100
  }
}

###
GET http://localhost:8080/information/api/person/12345678

###
DELETE http://localhost:8080/information/api/person/1/address

###
DELETE http://localhost:8080/information/api/phone/12345678

###
DELETE http://localhost:8080/information/api/person/1

###
GET http://localhost:8080/information/api/hobby

###
GET http://localhost:8080/information/api/hobby/count

###
GET http://localhost:8080/information/api/hobby/squash

###
GET http://localhost:8080/information/api/hobby/squash/persons

###
GET http://localhost:8080/information/api/hobby/squash/persons/count
